In [1]:
import numpy as np

In [4]:
# funkcje zaczerpnięte z https://tobiasraabe.github.io/post/numpy-views-vs-copies/
# dzięki nim łatwiej będzie nam interpretować czy dwie tablice numpy posiadają wspólną bazę
# co oznacza, że współdzielą pamięć (lub nie)

def get_data_base(x):
    base = x
    while isinstance(base.base, np.ndarray):
        base = base.base
    return base

def arrays_share_data(x, y):
    return get_data_base(x) is get_data_base(y)

In [5]:
#Zadanie 1
#Stwórz tablicę numpy o wymiarach (4,4) wypełnioną wartościami od 2 do 32
#z krokiem 2 i przypisz ją do zmiennej. Wyświetl jej typ danch, liczbę
#elementów, wielkość pojedynczego elementu oraz ilość zaalokowanej pamięci.
A = np.arange(2,34,2)
A = A.reshape(4,4)
print(A)
A.dtype, A.size, A.itemsize, A.nbytes

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


(dtype('int64'), 16, 8, 128)

In [6]:
#Zadanie 2
#Wróć tablicę z zadania 1 jako widok. Zmień jej typ danych (możesz to zrobić
# np. funkcją astype()) na np.uint8. Sprawdź teraz czy tablica jest widokiem
#czy kopią tablicy oryginalnej. Wyświetl jej liczbę elementów, wielkość
#pojedynczego elementu oraz ilość zaalokowanej pamięci.
B = A.view()
B = B.astype(np.uint8)
arrays_share_data(A, B)
print(B)
B.flags.owndata, B.size, B.itemsize, B.nbytes

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


(True, 16, 1, 16)

In [15]:
#Zadanie 3
#Wytnij z tablicy z zadania 1 obszar 2 x 2 "ze środka" tablicy (wartości 12,14, 20,22) na dwa sposoby:
#jeden jako widok i przypisz do zmiennej
C_1 = A[1:3, 1:3]
print(C_1)
arrays_share_data(A, C_1)

[[12 14]
 [20 22]]


True

In [16]:
#drugi jako kopia i przypisz do zmiennej
C_2 = A[1:3, 1:3].copy()
print(C_2)
arrays_share_data(A, C_2)

[[12 14]
 [20 22]]


False

In [18]:
#Zadanie 4
#Stwórz tablicę 4x4, która zawiera wartości 1,2,3,4 w każdym wierszu.
#Następnie wykorzystując funkcje łączenia tablic utwórz tablicę połączoną z
#powyższej tablicy i jej wersji lustrzanej w poziomie (spróbuj użyć wycinków).
D = np.arange(1, 5)
D = np.tile(D, (4, 1))
print(D)
D_mirror = D[:, ::-1]
print(D_mirror)
D_joined = np.hstack((D, D_mirror))
print(D_joined)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]]
[[1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]]


In [21]:
#Zadanie 5
#Utwórz tablicę o nazwie Z_5 o wymiarach 2x2 wypełnioną wartościami 1.
E = np.ones((2,2))
#Wykorzystując funkcje łączenia tabel uwtórz tablicę, która finalnie będzie
#tablicą składającą się z 4-ech tablic Z_5, ale tak aby finalnie była to tablica
#4 x 4 podobna do poniższej:
#1,1,2,2
#1,1,2,2
#3,3,4,4
#3,3,4,4
E_joined = np.vstack((np.hstack((E, E*2)), np.hstack((E*3, E*4))))
print(E_joined)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]
