<a href="https://colab.research.google.com/github/JedWojtowicz/MAD_jw/blob/main/JW_lab_03_PD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import numpy as np
from timeit import timeit

In [70]:
rng = np.random.default_rng()

In [71]:
#1.Stwórz tablicę o nazwie a_small_one o wymiarach 8x8 z wartościami od 1 do 64.
a_small_one = np.arange(1, 65).reshape(8, 8)
a_small_one

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [72]:
#2.Dla tablicy a_small_one policz:
#sumę dla każdej kolumny,
print("Suma dla kadej kolumny to:",a_small_one.sum(axis=0))
#sumę skumulowaną dla każdego wiersza,
print("Suma skumoulowana dla kadego wiersza to:",a_small_one.cumsum(axis=1))
#wartość średnią dla każdego wiersza
print("Wartoc srednia dla kazdego wiersza to:",a_small_one.mean(axis=0))

Suma dla kadej kolumny to: [232 240 248 256 264 272 280 288]
Suma skumoulowana dla kadego wiersza to: [[  1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100]
 [ 17  35  54  74  95 117 140 164]
 [ 25  51  78 106 135 165 196 228]
 [ 33  67 102 138 175 213 252 292]
 [ 41  83 126 170 215 261 308 356]
 [ 49  99 150 202 255 309 364 420]
 [ 57 115 174 234 295 357 420 484]]
Wartoc srednia dla kazdego wiersza to: [29. 30. 31. 32. 33. 34. 35. 36.]


In [73]:
#3.Zwróć podtablicę z tablicy a_small_one z elementami parzystymi (nie nadpisuj tej zmiennej).
arr_even = a_small_one.copy()
arr_even = arr_even[arr_even % 2 == 0]
arr_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])

In [74]:
#4.Zapisz do zmiennej o nazwie no_even_small_one tablicę a_small_one zamieniając wartości parzyste na wartość np.nan.
no_even_small_one = a_small_one.copy().astype(np.float64)
no_even_small_one[no_even_small_one % 2 == 0] = np.nan
no_even_small_one

array([[ 1., nan,  3., nan,  5., nan,  7., nan],
       [ 9., nan, 11., nan, 13., nan, 15., nan],
       [17., nan, 19., nan, 21., nan, 23., nan],
       [25., nan, 27., nan, 29., nan, 31., nan],
       [33., nan, 35., nan, 37., nan, 39., nan],
       [41., nan, 43., nan, 45., nan, 47., nan],
       [49., nan, 51., nan, 53., nan, 55., nan],
       [57., nan, 59., nan, 61., nan, 63., nan]])

In [75]:
#5.Dla tablicy no_even_small_one policz funkcjami uwzględniającymi wartości nan (zazwyczaj posiadają przedrostek nan):
#sumę dla każdego wiersza,
print("Suma dla kazdego wiersza:",np.nansum(no_even_small_one,axis=1))
#średnią dla każdej kolumny,
print("Srednia dla kazdej kolumny:",np.nanmean(no_even_small_one,axis=0))
#wartość najmniejszą w całej tablicy
print("Najmniejsza wartosc w calej tablicy:",np.nanmin(no_even_small_one))

Suma dla kazdego wiersza: [ 16.  48.  80. 112. 144. 176. 208. 240.]
Srednia dla kazdej kolumny: [29. nan 31. nan 33. nan 35. nan]
Najmniejsza wartosc w calej tablicy: 1.0


<ipython-input-75-6127b325b918>:5: RuntimeWarning: Mean of empty slice
  print("Srednia dla kazdej kolumny:",np.nanmean(no_even_small_one,axis=0))


In [76]:
#6.Do tablicy no_even_small_one wstaw za pomocą funkcji np.where:

#wartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję np.isnan())
no_even_small_one[np.isnan(no_even_small_one)] = 1
#print(no_even_small_one)

'''liczby parzyste, które wcześniej zastąpiliśmy wartościami nan (teraz 1 jeżeli
wykonany jest podpunkt pierwszy), więc przywracamy ten tablicy wygląd
oryginalny z tablicy a_small_one - dla warunku wstawiaj wartość z a_small_one
lub no_even_small_one'''

np.where(no_even_small_one == 1, a_small_one, no_even_small_one)

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30., 31., 32.],
       [33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48.],
       [49., 50., 51., 52., 53., 54., 55., 56.],
       [57., 58., 59., 60., 61., 62., 63., 64.]])

In [77]:
#7.Stwórz tablicę o nazwie sto_by_sto o wymiarach 100x100 próbkując wartości z rozkładu normalnego standardowego.
sto_by_sto = rng.normal(size=(100,100))
sto_by_sto

array([[ 1.48686082,  1.40075966, -0.19710105, ...,  0.16369403,
        -0.83566964, -1.56761522],
       [-0.60154601, -1.03493726, -0.18457707, ...,  0.49395352,
         0.37192963,  0.94738168],
       [-0.19625172, -0.70725171, -0.16671888, ..., -1.1380991 ,
        -0.1778147 , -0.53885566],
       ...,
       [ 0.22324587, -0.22235276,  2.32793521, ..., -0.40466433,
        -0.57901136,  0.38973305],
       [-0.75410144, -0.06149828,  0.30424583, ...,  0.53085025,
        -1.04044073, -0.42950623],
       [-0.02025435,  0.63596953,  1.13573674, ...,  0.76797825,
         2.02117967,  0.60165517]])

In [78]:
#8.Dla tablicy sto_by_sto policz:
#wartość średnią w każdym wierszu i kolumnie (oddzielnie),
print("Wartosć średnia w każdym wierszu:", np.mean(sto_by_sto, axis=1))
print("Wartość średnia w każdej kolumnie:", np.mean(sto_by_sto, axis=0))
'''
policz średnią różnicę bezwzględną dla wartości w powyższym punkcie względem
wartości 0 (oddzielnie dla średniej z kolumn i średniej z wierszy, pamiętam o
tym, że operacje na tablicy numpy wykonywane są w trybie broadcast)
'''
print(abs(np.mean(np.mean(sto_by_sto, axis=1))))
print(abs(np.mean(np.mean(sto_by_sto, axis=0))))

Wartosć średnia w każdym wierszu: [-0.1276968  -0.08181242 -0.00346127 -0.03551962 -0.03615045 -0.01393391
  0.06659385 -0.06753464 -0.05953458  0.08301949 -0.11725502  0.04395904
  0.1619065  -0.01635099  0.13587942  0.15175193  0.13713885  0.08048897
 -0.03382062  0.00563308 -0.06774663 -0.07745212  0.10362274  0.07428371
  0.07081183  0.0444748  -0.00267332  0.03595884  0.04026981  0.11281567
 -0.08364346  0.03349128  0.05262562 -0.05147759  0.12194659 -0.04351233
  0.01716245  0.19167248  0.04379003  0.2196834   0.12572693  0.0236418
 -0.0860264   0.00827398 -0.07536266  0.0465486   0.19202696  0.04394825
  0.07568688 -0.08663713 -0.01013862  0.01069979  0.08757984  0.19649617
  0.00388469  0.11911693  0.11726866  0.10816004  0.08387001  0.13424473
  0.05997856  0.13474441  0.02254062 -0.0541961  -0.13763855  0.08345157
  0.02192455 -0.004053   -0.11322737  0.03526745 -0.05277948  0.02547861
 -0.01894113  0.00302694  0.05065613  0.00438166  0.02995469 -0.1385362
  0.01520092  0.013

In [79]:
#9.Stwórz tablicę o wymiarach 1000x1000 uzupełniając ją wartościami losowymi z
#rozkładu normalnego standardowego, a następnie posiłkując się przykładami z
#labów poprzednich (moduł timeit) porównaj czasy wykonania dla tej tablicy:
tab1 = rng.normal(size=(1000,1000))
#zapisu do pliku tekstowego vs. zapis do pliku w formacie picle vs. zapis do
#pliku skompresowanego (funkcja savez_compressed w dokumentacji biblioteki numpy)
setup = """
import numpy as np
rng = np.random.default_rng()
tab1 = rng.normal(size=(1000,1000))
"""
stmt_1="""
np.savetxt('tab1.txt', tab1)
"""
stmt_2="""
np.save('tab1_pickle', tab1)
"""
stmt_3="""
np.savez_compressed('tab1.npz', tab1)
"""
timeit(stmt_1,setup=setup, number=10),timeit(stmt_2,setup=setup, number=10),timeit(stmt_3,setup=setup, number=10)

(10.446427216000302, 0.15182007800012798, 5.367167483999765)

In [80]:
#odczytu dla trzech wyżej wymienionych plików.
stmt_1_2="""
tab_from_file = np.loadtxt('tab1.txt')
"""
stmt_2_2="""
tab_from_file = np.load('tab1_pickle.npy')
"""
stmt_3_2="""
tab_from_file = np.load('tab1.npz')
"""
timeit(stmt_1_2,setup=setup, number=10),timeit(stmt_2_2,setup=setup, number=10),timeit(stmt_3_2,setup=setup, number=10)

(5.369558471000346, 0.02821663999930024, 0.001008942000225943)